name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    uses: ./.github/workflows/common/build-and-deploy.yml
    with:
      enable_sourcemaps: true
      fetch_depth: 0
      release_version: ${{ github.sha }}
    secrets: inherit
