name: Manual Deploy to GitHub Pages

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Build and Deploy
        uses: ./.github/actions/build-and-deploy
        with:
          enable_sourcemaps: 'false'
          fetch_depth: '1'
          github_token: ${{ secrets.GITHUB_TOKEN }}
